language: java
before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb http://download.mono-project.com/repo/ubuntu precise main" | sudo tee /etc/apt/sources.list.d/mono-official.list
    - sudo apt-get -qq update
    - sudo apt-get install -qq -y mono-xsp4
    - mono --version
sudo: true
jdk:
- oraclejdk8
- oraclejdk7

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- ./gradlew cobertura coveralls
