language: java
before_install:
    - ./travis/setup_linux.sh
    - mono --version
sudo: true
jdk:
- oraclejdk8
- oraclejdk7

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- ./gradlew cobertura coveralls
