language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-xsp4
  - mono --version
sudo: true
jdk:
- oraclejdk8
- oraclejdk7

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
- ./gradlew check --info

after_success:
- ./gradlew cobertura coveralls
