language: java
before_install:
    - ./travis/setup_linux.sh
    - mono --version
sudo: true
jdk:
- oraclejdk8
- oraclejdk7

env:
    global:
        - CI=true
        - CI_NAME=travis-ci

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- ./gradlew jacocoTestReport coveralls
