language: java

matrix:
  include:
    - os: linux
      sudo: true
      jdk: oraclejdk8
    - os: linux
      sudo: true
      jdk: oraclejdk7
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.3

before_install:
  - ./travis/setup_$TRAVIS_OS_NAME.sh
  - mono --version

env:
    global:
        - CI=true
        - CI_NAME=travis-ci

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- ./gradlew jacocoTestReport coveralls
