language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono
  
sudo: false
jdk:
- oraclejdk8
- oraclejdk7

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
